apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: myapp
          image: nginx:latest
          ports:
            - containerPort: 80
          env:
            - name: CLIENT_ID
              valueFrom:
                configMapKeyRef:
                  name: argo-runtime-config
                  key: client_id
            - name: VAULT_NAME
              valueFrom:
                configMapKeyRef:
                  name: argo-runtime-config
                  key: vault_name
            - name: REGISTRY_URL
              valueFrom:
                configMapKeyRef:
                  name: argo-runtime-config
                  key: registry_url
