apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: myapp
          image: nginx:latest
          ports:
            - containerPort: 80
          env:
            - name: CLIENT_ID
              value: {{- $cm := (lookup "v1" "ConfigMap" "default" "argo-runtime-config") -}}{{- if $cm }}{{ $cm.data.client_id | default "" }}{{- else }}""{{- end }}
            - name: VAULT_NAME
              value: {{- $cm := (lookup "v1" "ConfigMap" "default" "argo-runtime-config") -}}{{- if $cm }}{{ $cm.data.vault_name | default "" }}{{- else }}""{{- end }}
            - name: REGISTRY_URL
              value: {{- $cm := (lookup "v1" "ConfigMap" "default" "argo-runtime-config") -}}{{- if $cm }}{{ $cm.data.registry_url | default "" }}{{- else }}""{{- end }}
